package com.example.game3d.core.simulation;

public enum JumpRuleId {
    TERMINAL_REJECT,
    LANDING_CHARGED,
    GROUNDED_RELEASED,
    GROUNDED_BUFFERED,
    JUMP_COOLDOWN_DEFER,
    AIRBORNE_RELEASED,
    AIRBORNE_SPIKE_FIRST,
    AIRBORNE_UNRECOVERABLE,
    AIRBORNE_SAFE_SUPPORT_DEFER,
    AIRBORNE_NO_CHARGE_DEFER,
    AIRBORNE_NO_CHARGE_REJECT,
    CHARGE_EXPIRED,
    NO_REQUEST
}
